name: "databases"

services:
  redis:
    container_name: Redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    container_name: Postgres
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_bkia_website
      TZ: Asia/Vientiane
      PGTZ: Asia/Vientiane
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
