name: "bkia-website"

services:
  redis:
    container_name: Redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    container_name: Postgres
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: bkia
      POSTGRES_PASSWORD: bkia$admin@2425
      POSTGRES_DB: db_bkia_website
      TZ: Asia/Vientiane
      PGTZ: Asia/Vientiane
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web:
    container_name: web
    image: korvisedyotsaiy/bkia-website-uat:${IMAGE_TAG:-latest}
    restart: always
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ubuntu/ssl/certbot/www:/var/www/certbot
      - /home/ubuntu/ssl/certbot/conf:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /home/ubuntu/ssl/certbot/www:/var/www/certbot
      - /home/ubuntu/ssl/certbot/conf:/etc/letsencrypt
    entrypoint: sh
    command: -c "trap exit TERM; while :; do sleep 3600; done"

networks:
  app-network:
    driver: bridge
